baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rockhopperbrew.co" # the base hostname & protocol for your site

title: Rockhopper Brewing Co.
description: > # this means to ignore newlines until "baseurl:"
  Rockhopper Brewing Company is a Bedfordshire (UK) based brewery founded in
  2015.

email: info@rockhopperbrew.co
phone: "07879 810 558"

twitter: https://twitter.com/hopperbrew
facebook: https://www.facebook.com/hopperbrew
googleplus: https://www.google.com/+Rockhopperbrew

# Build settings
encoding: utf-8
permalink: /news/:year/:month/:title/
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']

gems:
  - jekyll-sitemap
  - jekyll-assets

kramdown:
  input: GFM

assets:
  compress:
    css: default
    js: default
  digest: true
  cache: default
  cdn: https://assets.rockhopperbrew.co
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: '/assets'
  assets:
    - '*.png'
    - '*.jpg'
  sources:
    - 'assets/img'
    - 'assets/css'
    - 'assets/js'
