baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rockhopperbrew.co" # the base hostname & protocol for your site

title: Rockhopper Brewing Co.
description: > # this means to ignore newlines until "baseurl:"
  Rockhopper Brewing Company is a Bedfordshire (UK) based brewery founded in
  2015.

email: info@rockhopperbrew.co
phone: "07879 810 558"

twitter_username: hopperbrew
facebook_username: hopperbrew

# Build settings
encoding: utf-8
permalink: /news/:year/:month/:title
markdown: kramdown

kramdown:
  input: GFM
